language: scala
git:
  depth: 9999
scala:
- 2.11.6
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" &&
        "$TRAVIS_BRANCH" == "master" &&
        $(cat version.sbt) =~ "-SNAPSHOT"
  ]]; then
    sbt ++$TRAVIS_SCALA_VERSION coverage validate coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean validate publish gitSnapshots publish ;
  else
    sbt ++$TRAVIS_SCALA_VERSION coverage validate coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean validate publishLocal ;
  fi